name: kodi-unofficial
version: 0.1
summary: Kodi®, award-winning free and open source (GPL) software media center
description: | 
  Kodi® (formerly known as XBMC™) is an award-winning free and open source (GPL) software media center for playing videos, music, pictures, games, and more. Kodi runs on Linux, OS X, Windows, iOS, and Android, featuring a 10-foot user interface for use with televisions and remote controls. It allows users to play and view most videos, music, podcasts, and other digital media files from local and network storage media and the internet.
confinement: devmode

apps:
  kodi:
    command: 
    daemon: 
    plugs: [network, home, network-bind]

parts:
  kodi:
    plugin: autotools
    source: git://github.com/xbmc/xbmc.git
    source-type: git
    build-packages:
      - automake
      - autopoint
      - bison
      - build-essential
      - ccache
      - cmake
      - curl
      - cvs
      - default-jre
      - fp-compiler
      - gawk
      - gdc
      - gettext
      - git-core
      - gperf
      - nasm
      - pmount
      - python-dev
      - python-imaging
      - python-sqlite
      - swig
      - unzip
      - yasm
      - zip
      - zlib1g-dev
    stage-packages:
      - libasound2-dev
      - libass-dev
      - libavcodec-dev
      - libavfilter-dev
      - libavformat-dev
      - libavutil-dev
      - libbluetooth-dev
      - libbluray-dev
      - libbluray1
      - libboost-dev
      - libboost-thread-dev
      - libbz2-dev
      - libcap-dev
      - libcdio-dev
      - libcec-dev
      - libcec1
      - libcrystalhd-dev
      - libcrystalhd3
      - libcurl3
      - libcurl4-gnutls-dev
      - libcwiid-dev
      - libcwiid1
      - libdbus-1-dev
      - libenca-dev
      - libflac-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libglew-dev
      - libiso9660-dev
      - libjasper-dev
      - libjpeg-dev
      - libltdl-dev
      - liblzo2-dev
      - libmad0-dev
      - libmicrohttpd-dev
      - libmodplug-dev
      - libmp3lame-dev
      - libmpeg2-4-dev
      - libmpeg3-dev
      - libmysqlclient-dev
      - libnfs-dev
      - libogg-dev
      - libpcre3-dev
      - libplist-dev
      - libpng-dev
      - libpostproc-dev
      - libpulse-dev
      - libsamplerate-dev
      - libsdl-dev
      - libsdl-gfx1.2-dev
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libshairport-dev
      - libsmbclient-dev
      - libsqlite3-dev
      - libssh-dev
      - libssl-dev
      - libswscale-dev
      - libtiff-dev
      - libtinyxml-dev
      - libtool
      - libudev-dev
      - libusb-dev
      - libva-dev
      - libva-egl1
      - libva-tpi1
      - libvdpau-dev
      - libvorbisenc2
      - libxml2-dev
      - libxmu-dev
      - libxrandr-dev
      - libxrender-dev
      - libxslt1-dev
      - libxt-dev
      - libyajl-dev
      - mesa-utils

